import { Building, ShopItem, Boost, BuildingCategory } from './types';

export const BUILDINGS: Building[] = [
  // RESIDENTIAL BUILDINGS
  {
    id: 'small-house',
    name: 'Small House',
    description: 'A cozy starter home for a small family',
    category: 'residential',
    rarity: 'common',
    price: 50,
    size: { width: 1, height: 1 },
    income: 5,
    socialBoost: 1.0,
    unlockLevel: 1,
    sprite: 'house',
    color: '#22c55e',
    accentColor: '#4ade80',
    population: 4,
  },
  {
    id: 'apartment-building',
    name: 'Apartment Building',
    description: 'Multi-family housing for growing populations',
    category: 'residential',
    rarity: 'uncommon',
    price: 200,
    size: { width: 2, height: 2 },
    income: 20,
    socialBoost: 1.1,
    unlockLevel: 3,
    sprite: 'apartment',
    color: '#16a34a',
    accentColor: '#22c55e',
    population: 20,
  },
  {
    id: 'luxury-condo',
    name: 'Luxury Condos',
    description: 'High-end living for wealthy residents',
    category: 'residential',
    rarity: 'rare',
    price: 1000,
    size: { width: 2, height: 2 },
    income: 100,
    socialBoost: 1.3,
    unlockLevel: 8,
    sprite: 'condo',
    color: '#15803d',
    accentColor: '#16a34a',
    animation: 'glow',
    population: 50,
  },

  // COMMERCIAL BUILDINGS
  {
    id: 'corner-shop',
    name: 'Corner Shop',
    description: 'A small neighborhood convenience store',
    category: 'commercial',
    rarity: 'common',
    price: 75,
    size: { width: 1, height: 1 },
    income: 8,
    socialBoost: 1.05,
    unlockLevel: 1,
    sprite: 'shop',
    color: '#3b82f6',
    accentColor: '#60a5fa',
    jobs: 3,
  },
  {
    id: 'office-tower',
    name: 'Office Tower',
    description: 'Modern workspace for businesses',
    category: 'commercial',
    rarity: 'uncommon',
    price: 300,
    size: { width: 2, height: 2 },
    income: 30,
    socialBoost: 1.15,
    unlockLevel: 4,
    sprite: 'office',
    color: '#2563eb',
    accentColor: '#3b82f6',
    animation: 'pulse',
    jobs: 50,
  },
  {
    id: 'shopping-mall',
    name: 'Shopping Mall',
    description: 'Major retail destination',
    category: 'commercial',
    rarity: 'rare',
    price: 2000,
    size: { width: 3, height: 3 },
    income: 200,
    socialBoost: 1.4,
    unlockLevel: 10,
    sprite: 'mall',
    color: '#1d4ed8',
    accentColor: '#2563eb',
    animation: 'glow',
    jobs: 200,
  },

  // INDUSTRIAL BUILDINGS
  {
    id: 'small-factory',
    name: 'Small Factory',
    description: 'Light manufacturing facility',
    category: 'industrial',
    rarity: 'common',
    price: 100,
    size: { width: 2, height: 1 },
    income: 12,
    socialBoost: 0.9,
    unlockLevel: 2,
    sprite: 'factory',
    color: '#eab308',
    accentColor: '#facc15',
    jobs: 20,
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    description: 'Storage and distribution center',
    category: 'industrial',
    rarity: 'uncommon',
    price: 250,
    size: { width: 2, height: 2 },
    income: 25,
    socialBoost: 0.95,
    unlockLevel: 5,
    sprite: 'warehouse',
    color: '#ca8a04',
    accentColor: '#eab308',
    jobs: 30,
  },
  {
    id: 'heavy-industry',
    name: 'Heavy Industry',
    description: 'Large-scale manufacturing complex',
    category: 'industrial',
    rarity: 'rare',
    price: 1500,
    size: { width: 3, height: 2 },
    income: 150,
    socialBoost: 0.8,
    unlockLevel: 12,
    sprite: 'industry',
    color: '#a16207',
    accentColor: '#ca8a04',
    animation: 'pulse',
    jobs: 150,
  },

  // INFRASTRUCTURE
  {
    id: 'power-plant',
    name: 'Power Plant',
    description: 'Generates electricity for the city',
    category: 'infrastructure',
    rarity: 'rare',
    price: 2000,
    size: { width: 2, height: 2 },
    income: 0,
    socialBoost: 1.0,
    unlockLevel: 5,
    sprite: 'power',
    color: '#f97316',
    accentColor: '#fb923c',
    animation: 'pulse',
    powerConsumption: -100, // Generates power
  },
  {
    id: 'water-tower',
    name: 'Water Tower',
    description: 'Provides water to nearby buildings',
    category: 'infrastructure',
    rarity: 'uncommon',
    price: 500,
    size: { width: 1, height: 1 },
    income: 0,
    socialBoost: 1.0,
    unlockLevel: 3,
    sprite: 'water',
    color: '#06b6d4',
    accentColor: '#22d3ee',
    waterConsumption: -50, // Provides water
  },
  {
    id: 'transit-hub',
    name: 'Transit Hub',
    description: 'Central station connecting all areas',
    category: 'infrastructure',
    rarity: 'epic',
    price: 5000,
    size: { width: 3, height: 2 },
    income: 50,
    socialBoost: 1.5,
    unlockLevel: 15,
    sprite: 'transit',
    color: '#8b5cf6',
    accentColor: '#a78bfa',
    animation: 'glow',
  },

  // SERVICES
  {
    id: 'police-station',
    name: 'Police Station',
    description: 'Keeps the neighborhood safe',
    category: 'services',
    rarity: 'uncommon',
    price: 500,
    size: { width: 2, height: 1 },
    income: 0,
    socialBoost: 1.2,
    unlockLevel: 4,
    sprite: 'police',
    color: '#1e40af',
    accentColor: '#2563eb',
  },
  {
    id: 'fire-station',
    name: 'Fire Station',
    description: 'Emergency fire response',
    category: 'services',
    rarity: 'uncommon',
    price: 500,
    size: { width: 2, height: 1 },
    income: 0,
    socialBoost: 1.2,
    unlockLevel: 4,
    sprite: 'fire',
    color: '#dc2626',
    accentColor: '#ef4444',
  },
  {
    id: 'hospital',
    name: 'Hospital',
    description: 'Provides healthcare to citizens',
    category: 'services',
    rarity: 'rare',
    price: 1500,
    size: { width: 3, height: 2 },
    income: 0,
    socialBoost: 1.3,
    unlockLevel: 8,
    sprite: 'hospital',
    color: '#e11d48',
    accentColor: '#f43f5e',
    animation: 'pulse',
  },
  {
    id: 'school',
    name: 'School',
    description: 'Educates the youth',
    category: 'services',
    rarity: 'uncommon',
    price: 750,
    size: { width: 2, height: 2 },
    income: 0,
    socialBoost: 1.25,
    unlockLevel: 5,
    sprite: 'school',
    color: '#7c3aed',
    accentColor: '#8b5cf6',
  },

  // ENTERTAINMENT
  {
    id: 'park',
    name: 'City Park',
    description: 'Green space for relaxation',
    category: 'entertainment',
    rarity: 'common',
    price: 100,
    size: { width: 2, height: 2 },
    income: 5,
    socialBoost: 1.15,
    unlockLevel: 1,
    sprite: 'park',
    color: '#22c55e',
    accentColor: '#4ade80',
  },
  {
    id: 'stadium',
    name: 'Stadium',
    description: 'Sports and entertainment venue',
    category: 'entertainment',
    rarity: 'epic',
    price: 10000,
    size: { width: 4, height: 4 },
    income: 500,
    socialBoost: 1.5,
    unlockLevel: 15,
    sprite: 'stadium',
    color: '#ec4899',
    accentColor: '#f472b6',
    animation: 'glow',
    jobs: 100,
  },
  {
    id: 'amusement-park',
    name: 'Amusement Park',
    description: 'Fun for the whole family',
    category: 'entertainment',
    rarity: 'legendary',
    price: 25000,
    size: { width: 5, height: 5 },
    income: 1000,
    socialBoost: 2.0,
    unlockLevel: 20,
    sprite: 'amusement',
    color: '#f97316',
    accentColor: '#fb923c',
    animation: 'sparkle',
    jobs: 200,
  },

  // PREMIUM BUILDINGS
  {
    id: 'city-hall',
    name: 'City Hall',
    description: 'The seat of city government',
    category: 'premium',
    rarity: 'legendary',
    price: 50000,
    premiumPrice: 9.99,
    size: { width: 3, height: 3 },
    income: 500,
    socialBoost: 2.5,
    unlockLevel: 25,
    sprite: 'cityhall',
    color: '#8b5cf6',
    accentColor: '#a78bfa',
    animation: 'sparkle',
  },
  {
    id: 'space-center',
    name: 'Space Center',
    description: 'Reaching for the stars',
    category: 'premium',
    rarity: 'legendary',
    price: 100000,
    premiumPrice: 19.99,
    size: { width: 4, height: 4 },
    income: 2000,
    socialBoost: 3.0,
    unlockLevel: 35,
    sprite: 'space',
    color: '#1e3a8a',
    accentColor: '#3b82f6',
    animation: 'sparkle',
    jobs: 500,
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'starter-pack',
    name: 'Starter Pack',
    description: 'Perfect for new city builders',
    castAmount: 1000,
    usdPrice: 0.99,
  },
  {
    id: 'builder-bundle',
    name: 'Builder Bundle',
    description: 'Great value for growing cities',
    castAmount: 5000,
    usdPrice: 3.99,
    bonus: 10,
  },
  {
    id: 'mayor-pack',
    name: 'Mayor Pack',
    description: 'For serious city planners',
    castAmount: 15000,
    usdPrice: 9.99,
    bonus: 20,
    popular: true,
  },
  {
    id: 'tycoon-deal',
    name: 'Tycoon Deal',
    description: 'Maximum value for empire builders',
    castAmount: 50000,
    usdPrice: 24.99,
    bonus: 35,
  },
];

export const BOOSTS: Boost[] = [
  {
    id: '2x-income',
    name: '2x Income Boost',
    description: 'Double all building income',
    multiplier: 2,
    duration: 1,
    price: 500,
    active: false,
  },
  {
    id: '3x-income',
    name: '3x Income Boost',
    description: 'Triple all building income',
    multiplier: 3,
    duration: 4,
    price: 1500,
    active: false,
  },
  {
    id: '5x-speed',
    name: '5x Construction Speed',
    description: 'Buildings construct 5x faster',
    multiplier: 5,
    duration: 2,
    price: 1000,
    active: false,
  },
];

export const getBuildingById = (id: string): Building | undefined => {
  return BUILDINGS.find(b => b.id === id);
};

export const getBuildingsByCategory = (category: BuildingCategory): Building[] => {
  return BUILDINGS.filter(b => b.category === category);
};

export const getAffordableBuildings = (cast: number, level: number): Building[] => {
  return BUILDINGS.filter(b => b.price <= cast && b.unlockLevel <= level);
};

export const getUnlockedBuildings = (level: number): Building[] => {
  return BUILDINGS.filter(b => b.unlockLevel <= level);
};

export const getLockedBuildings = (level: number): Building[] => {
  return BUILDINGS.filter(b => b.unlockLevel > level);
};
